#!/usr/bin/env node
// Export the v2 whale's poster poses as contour data for src/whale.rs.
//
//   node tools/export-whale.cjs <path-to-whale-character-v2> [--check]
//
// The whale-character-v2 kit (acting.js + rig.js + props.js) is the executable
// oracle for the whale's pose. This script runs its Director exactly the way
// braille-demo.cjs does for a still (seed 11, reduced motion), evaluates the
// scene at each exported optical size, resolves compound holes with
// WhaleRig.holesFor, and writes every visible contour at full precision.
// Rounding is not safe: a 0.001 shift moves scanline crossings and changes
// the Braille stills. The Rust renderer then rasterizes these contours with
// the same even-odd algorithm as braille.js.
'use strict';
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const dir = args.find((a) => !a.startsWith('--'));
const check = args.includes('--check');
if (!dir) {
  console.error('usage: export-whale.cjs <whale-character-v2 dir> [--check]');
  process.exit(2);
}
for (const n of ['mark-data', 'rig', 'props', 'acting', 'catalogue', 'braille']) {
  require(path.resolve(dir, n + '.js'));
}
const { WhaleActing: A, WhaleRig: R, WhaleCatalogue: C } = globalThis;

// state key, calves. Pod always draws its calves; 1-3 are the only honest counts.
const SCENES = [
  ['rest', 0], ['busy', 0], ['needs', 0], ['done', 0],
  ['pod', 1], ['pod', 2], ['pod', 3],
];
// Optical sizes: 40 = 20x10 cells (compact), 64 = 32x16 cells (default).
const SIZES = [40, 64];

function director(key, calves) {
  const chosen = C.CASES.find((c) => c[0] === key);
  const d = new A.Director({ seed: 11, reduced: true });
  d.set(
    chosen[2],
    chosen[3] ? { kind: chosen[3], observed: chosen[3] !== 'unknown', parallel: calves || 3 } : null,
    { freshness: 'Live', turnId: 'terminal-demo', status: 'completed', nowMs: 1000, failedAtMs: 0 },
  );
  return d;
}

const num = (v) => {
  if (!Number.isFinite(v)) throw new Error('non-finite coordinate');
  return String(v);
};

const out = [
  '# Codewhale v2 whale poster contours. Generated by tools/export-whale.cjs; do not edit.',
  '# Source: codewhale-app vendor/whale-character-v2 (acting.js, rig.js, props.js, mark-data.js).',
  '# scene <state> <calves> <size> | shape <id> <role> | path x y (c1x c1y c2x c2y x y)* ; closed',
];
for (const [key, calves] of SCENES) {
  for (const size of SIZES) {
    const scene = A.scene(director(key, calves), { dir: 'mark', size, lod: 2, dpr: 1 });
    out.push(`scene ${key} ${calves} ${size}`);
    for (const shape of scene.shapes) {
      if (shape.opacity < 0.5 || shape.role === 'hole' || shape.role === 'cutout') continue;
      out.push(`shape ${shape.id} ${shape.role}`);
      for (const p of [shape.path, ...R.holesFor(shape.id, scene.shapes, true)]) {
        const sig = p.map((c) => c[0]).join('');
        if (!/^MC*Z$/.test(sig)) throw new Error(`unexpected path shape ${sig} in ${shape.id}`);
        const nums = [...p[0].slice(1)];
        for (const c of p.slice(1, -1)) nums.push(...c.slice(1));
        out.push('path ' + nums.map(num).join(' '));
      }
    }
  }
}
const text = out.join('\n') + '\n';
const target = path.resolve(__dirname, '..', 'assets', 'whale-v2.scenes');
if (check) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== text) {
    console.error('assets/whale-v2.scenes is stale; rerun without --check');
    process.exit(1);
  }
  console.log('whale scenes verified');
} else {
  fs.writeFileSync(target, text);
  console.log(`wrote ${target} (${text.length} bytes)`);
}
